# Generated by Django 5.2.8 on 2025-12-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('isbn', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
