[project]
name = "bookwatcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.0",
    "fastapi[standard]>=0.119.1",
    "python-ulid>=3.1.0",
    "sqlalchemy>=2.0.44",
]
